// Class spell list mappings for D&D 5e 2024
// Maps spell names to the classes that can learn them
// This is necessary because the 5etools XPHB data doesn't include class associations yet

export const CLASS_SPELL_LISTS: Record<string, string[]> = {
  // CANTRIPS (Level 0)
  "acid splash": ["sorcerer", "wizard"],
  "blade ward": ["bard", "sorcerer", "warlock", "wizard"],
  "chill touch": ["sorcerer", "warlock", "wizard"],
  "dancing lights": ["bard", "sorcerer", "wizard"],
  "druidcraft": ["druid"],
  "eldritch blast": ["warlock"],
  "elementalism": ["druid", "sorcerer", "wizard"],
  "fire bolt": ["sorcerer", "wizard"],
  "friends": ["bard", "sorcerer", "warlock", "wizard"],
  "guidance": ["cleric", "druid"],
  "light": ["bard", "cleric", "sorcerer", "wizard"],
  "mage hand": ["bard", "sorcerer", "warlock", "wizard"],
  "mending": ["bard", "cleric", "druid", "sorcerer", "wizard"],
  "message": ["bard", "sorcerer", "wizard"],
  "mind sliver": ["sorcerer", "warlock", "wizard"],
  "minor illusion": ["bard", "sorcerer", "warlock", "wizard"],
  "poison spray": ["druid", "sorcerer", "warlock", "wizard"],
  "prestidigitation": ["bard", "sorcerer", "warlock", "wizard"],
  "produce flame": ["druid"],
  "ray of frost": ["sorcerer", "wizard"],
  "resistance": ["cleric", "druid"],
  "sacred flame": ["cleric"],
  "shillelagh": ["druid"],
  "shocking grasp": ["sorcerer", "wizard"],
  "spare the dying": ["cleric"],
  "starry wisp": ["bard", "druid"],
  "thaumaturgy": ["cleric"],
  "thorn whip": ["druid"],
  "thunderclap": ["bard", "druid", "sorcerer", "wizard"],
  "true strike": ["bard", "sorcerer", "warlock", "wizard"],
  "vicious mockery": ["bard"],

  // Level 1
  "alarm": ["ranger", "wizard"],
  "animal friendship": ["bard", "druid", "ranger"],
  "armor of agathys": ["warlock"],
  "arms of hadar": ["warlock"],
  "bane": ["bard", "cleric"],
  "bless": ["cleric", "paladin"],
  "burning hands": ["sorcerer", "wizard"],
  "charm person": ["bard", "druid", "sorcerer", "warlock", "wizard"],
  "chromatic orb": ["sorcerer", "wizard"],
  "color spray": ["sorcerer", "wizard"],
  "command": ["cleric", "paladin"],
  "compelled duel": ["paladin"],
  "comprehend languages": ["bard", "sorcerer", "warlock", "wizard"],
  "create or destroy water": ["cleric", "druid"],
  "cure wounds": ["bard", "cleric", "druid", "paladin", "ranger"],
  "detect evil and good": ["cleric", "paladin"],
  "detect magic": ["bard", "cleric", "druid", "paladin", "ranger", "sorcerer", "wizard"],
  "detect poison and disease": ["cleric", "druid", "paladin", "ranger"],
  "disguise self": ["bard", "sorcerer", "wizard"],
  "dissonant whispers": ["bard"],
  "divine favor": ["paladin"],
  "divine smite": ["paladin"],
  "ensnaring strike": ["ranger"],
  "entangle": ["druid"],
  "expeditious retreat": ["sorcerer", "warlock", "wizard"],
  "faerie fire": ["bard", "druid"],
  "false life": ["sorcerer", "wizard"],
  "feather fall": ["bard", "sorcerer", "wizard"],
  "find familiar": ["wizard"],
  "fog cloud": ["druid", "ranger", "sorcerer", "wizard"],
  "goodberry": ["druid", "ranger"],
  "grease": ["wizard"],
  "guiding bolt": ["cleric"],
  "healing word": ["bard", "cleric", "druid"],
  "hellish rebuke": ["warlock"],
  "heroism": ["bard", "paladin"],
  "hex": ["warlock"],
  "hunter's mark": ["ranger"],
  "identify": ["bard", "wizard"],
  "illusory script": ["bard", "warlock", "wizard"],
  "inflict wounds": ["cleric"],
  "jump": ["druid", "ranger", "sorcerer", "wizard"],
  "longstrider": ["bard", "druid", "ranger", "wizard"],
  "mage armor": ["sorcerer", "wizard"],
  "magic missile": ["sorcerer", "wizard"],
  "protection from evil and good": ["cleric", "paladin", "warlock", "wizard"],
  "purify food and drink": ["cleric", "druid", "paladin"],
  "ray of sickness": ["sorcerer", "wizard"],
  "sanctuary": ["cleric"],
  "shield": ["sorcerer", "wizard"],
  "shield of faith": ["cleric", "paladin"],
  "silent image": ["bard", "sorcerer", "wizard"],
  "sleep": ["bard", "sorcerer", "wizard"],
  "speak with animals": ["bard", "druid", "ranger"],
  "thunderwave": ["bard", "druid", "sorcerer", "wizard"],
  "unseen servant": ["bard", "warlock", "wizard"],
  "witch bolt": ["sorcerer", "warlock", "wizard"],

  // Level 2
  "aid": ["cleric", "paladin"],
  "alter self": ["sorcerer", "wizard"],
  "animal messenger": ["bard", "druid", "ranger"],
  "arcane lock": ["wizard"],
  "augury": ["cleric"],
  "barkskin": ["druid", "ranger"],
  "beast sense": ["druid", "ranger"],
  "blindness/deafness": ["bard", "cleric", "sorcerer", "wizard"],
  "blur": ["sorcerer", "wizard"],
  "calm emotions": ["bard", "cleric"],
  "cloud of daggers": ["bard", "sorcerer", "warlock", "wizard"],
  "continual flame": ["cleric", "wizard"],
  "crown of madness": ["bard", "sorcerer", "warlock", "wizard"],
  "darkness": ["sorcerer", "warlock", "wizard"],
  "darkvision": ["druid", "ranger", "sorcerer", "wizard"],
  "detect thoughts": ["bard", "sorcerer", "wizard"],
  "enhance ability": ["bard", "cleric", "druid", "sorcerer"],
  "enlarge/reduce": ["sorcerer", "wizard"],
  "enthrall": ["bard", "warlock"],
  "find steed": ["paladin"],
  "flame blade": ["druid"],
  "flaming sphere": ["druid", "wizard"],
  "gentle repose": ["cleric", "wizard"],
  "gust of wind": ["druid", "sorcerer", "wizard"],
  "heat metal": ["bard", "druid"],
  "hold person": ["bard", "cleric", "druid", "sorcerer", "warlock", "wizard"],
  "invisibility": ["bard", "sorcerer", "warlock", "wizard"],
  "knock": ["bard", "sorcerer", "wizard"],
  "lesser restoration": ["bard", "cleric", "druid", "paladin", "ranger"],
  "levitate": ["sorcerer", "wizard"],
  "locate animals or plants": ["bard", "druid", "ranger"],
  "locate object": ["bard", "cleric", "druid", "paladin", "ranger", "wizard"],
  "magic weapon": ["paladin", "wizard"],
  "mirror image": ["sorcerer", "warlock", "wizard"],
  "misty step": ["sorcerer", "warlock", "wizard"],
  "moonbeam": ["druid"],
  "pass without trace": ["druid", "ranger"],
  "prayer of healing": ["cleric"],
  "protection from poison": ["cleric", "druid", "paladin", "ranger"],
  "ray of enfeeblement": ["warlock", "wizard"],
  "scorching ray": ["sorcerer", "wizard"],
  "see invisibility": ["bard", "sorcerer", "wizard"],
  "shatter": ["bard", "sorcerer", "warlock", "wizard"],
  "silence": ["bard", "cleric", "ranger"],
  "spider climb": ["sorcerer", "warlock", "wizard"],
  "spike growth": ["druid", "ranger"],
  "spiritual weapon": ["cleric"],
  "suggestion": ["bard", "sorcerer", "warlock", "wizard"],
  "warding bond": ["cleric"],
  "web": ["sorcerer", "wizard"],
  "zone of truth": ["bard", "cleric", "paladin"],

  // Level 3
  "animate dead": ["cleric", "wizard"],
  "aura of vitality": ["cleric", "druid", "paladin"],
  "beacon of hope": ["cleric"],
  "bestow curse": ["bard", "cleric", "wizard"],
  "blink": ["sorcerer", "wizard"],
  "call lightning": ["druid"],
  "clairvoyance": ["bard", "cleric", "sorcerer", "wizard"],
  "conjure animals": ["druid", "ranger"],
  "conjure barrage": ["ranger"],
  "counterspell": ["sorcerer", "warlock", "wizard"],
  "crusader's mantle": ["paladin"],
  "daylight": ["cleric", "druid", "paladin", "ranger", "sorcerer"],
  "dispel magic": ["bard", "cleric", "druid", "paladin", "sorcerer", "warlock", "wizard"],
  "elemental weapon": ["paladin", "ranger"],
  "fear": ["bard", "sorcerer", "warlock", "wizard"],
  "feign death": ["bard", "cleric", "druid", "wizard"],
  "fireball": ["sorcerer", "wizard"],
  "fly": ["sorcerer", "warlock", "wizard"],
  "gaseous form": ["sorcerer", "warlock", "wizard"],
  "glyph of warding": ["bard", "cleric", "wizard"],
  "haste": ["sorcerer", "wizard"],
  "hunger of hadar": ["warlock"],
  "hypnotic pattern": ["bard", "sorcerer", "warlock", "wizard"],
  "lightning bolt": ["sorcerer", "wizard"],
  "magic circle": ["cleric", "paladin", "warlock", "wizard"],
  "major image": ["bard", "sorcerer", "warlock", "wizard"],
  "mass healing word": ["cleric"],
  "meld into stone": ["cleric", "druid", "ranger"],
  "plant growth": ["bard", "druid", "ranger"],
  "protection from energy": ["cleric", "druid", "ranger", "sorcerer", "wizard"],
  "remove curse": ["cleric", "paladin", "warlock", "wizard"],
  "revivify": ["cleric", "druid", "paladin", "ranger"],
  "sleet storm": ["druid", "sorcerer", "wizard"],
  "slow": ["sorcerer", "wizard"],
  "speak with dead": ["bard", "cleric"],
  "spirit guardians": ["cleric"],
  "stinking cloud": ["bard", "sorcerer", "wizard"],
  "tongues": ["bard", "cleric", "sorcerer", "warlock", "wizard"],
  "vampiric touch": ["sorcerer", "warlock", "wizard"],
  "water breathing": ["druid", "ranger", "sorcerer", "wizard"],
  "water walk": ["cleric", "druid", "ranger", "sorcerer"],
  "wind wall": ["druid", "ranger"],

  // Level 4
  "arcane eye": ["wizard"],
  "aura of life": ["paladin"],
  "aura of purity": ["paladin"],
  "banishment": ["cleric", "paladin", "sorcerer", "warlock", "wizard"],
  "blight": ["druid", "sorcerer", "warlock", "wizard"],
  "compulsion": ["bard"],
  "confusion": ["bard", "druid", "sorcerer", "wizard"],
  "conjure minor elementals": ["druid", "wizard"],
  "conjure woodland beings": ["druid", "ranger"],
  "control water": ["cleric", "druid", "wizard"],
  "death ward": ["cleric", "paladin"],
  "dimension door": ["bard", "sorcerer", "warlock", "wizard"],
  "divination": ["cleric", "druid"],
  "dominate beast": ["druid", "sorcerer"],
  "fabricate": ["wizard"],
  "faithful hound": ["wizard"],
  "fire shield": ["sorcerer", "wizard"],
  "freedom of movement": ["bard", "cleric", "druid", "ranger"],
  "giant insect": ["druid"],
  "grasping vine": ["druid", "ranger"],
  "greater invisibility": ["bard", "sorcerer", "wizard"],
  "guardian of faith": ["cleric"],
  "hallucinatory terrain": ["bard", "druid", "warlock", "wizard"],
  "ice storm": ["druid", "sorcerer", "wizard"],
  "locate creature": ["bard", "cleric", "druid", "paladin", "ranger", "wizard"],
  "polymorph": ["bard", "druid", "sorcerer", "wizard"],
  "stone shape": ["cleric", "druid", "wizard"],
  "stoneskin": ["druid", "ranger", "sorcerer", "wizard"],
  "wall of fire": ["druid", "sorcerer", "wizard"],

  // Level 5
  "animate objects": ["bard", "sorcerer", "wizard"],
  "antilife shell": ["druid"],
  "awaken": ["bard", "druid"],
  "banishing smite": ["paladin"],
  "bigby's hand": ["sorcerer", "wizard"],
  "cloudkill": ["sorcerer", "wizard"],
  "commune": ["cleric"],
  "commune with nature": ["druid", "ranger"],
  "cone of cold": ["sorcerer", "wizard"],
  "conjure elemental": ["druid", "wizard"],
  "contact other plane": ["warlock", "wizard"],
  "contagion": ["cleric", "druid"],
  "creation": ["sorcerer", "wizard"],
  "destructive wave": ["paladin"],
  "dispel evil and good": ["cleric", "paladin"],
  "dominate person": ["bard", "sorcerer", "wizard"],
  "dream": ["bard", "warlock", "wizard"],
  "flame strike": ["cleric"],
  "geas": ["bard", "cleric", "druid", "paladin", "wizard"],
  "greater restoration": ["bard", "cleric", "druid", "ranger"],
  "hallow": ["cleric"],
  "hold monster": ["bard", "sorcerer", "warlock", "wizard"],
  "insect plague": ["cleric", "druid", "sorcerer"],
  "legend lore": ["bard", "cleric", "wizard"],
  "mass cure wounds": ["bard", "cleric", "druid"],
  "mislead": ["bard", "sorcerer", "wizard"],
  "modify memory": ["bard", "wizard"],
  "passwall": ["wizard"],
  "planar binding": ["bard", "cleric", "druid", "wizard"],
  "raise dead": ["bard", "cleric", "paladin"],
  "reincarnate": ["druid"],
  "scrying": ["bard", "cleric", "druid", "warlock", "wizard"],
  "seeming": ["bard", "sorcerer", "wizard"],
  "skill empowerment": ["bard", "sorcerer", "wizard"],
  "steel wind strike": ["ranger", "wizard"],
  "telekinesis": ["sorcerer", "wizard"],
  "teleportation circle": ["bard", "sorcerer", "wizard"],
  "tree stride": ["druid", "ranger"],
  "wall of force": ["wizard"],
  "wall of stone": ["druid", "sorcerer", "wizard"],

  // Level 6
  "arcane gate": ["sorcerer", "warlock", "wizard"],
  "blade barrier": ["cleric"],
  "bones of the earth": ["druid"],
  "chain lightning": ["sorcerer", "wizard"],
  "circle of death": ["sorcerer", "warlock", "wizard"],
  "conjure fey": ["druid", "warlock"],
  "contingency": ["wizard"],
  "create undead": ["cleric", "warlock", "wizard"],
  "disintegrate": ["sorcerer", "wizard"],
  "eyebite": ["bard", "sorcerer", "warlock", "wizard"],
  "find the path": ["bard", "cleric", "druid"],
  "flesh to stone": ["warlock", "wizard"],
  "forbiddance": ["cleric"],
  "globe of invulnerability": ["sorcerer", "wizard"],
  "guards and wards": ["bard", "wizard"],
  "harm": ["cleric"],
  "heal": ["cleric", "druid"],
  "heroes' feast": ["cleric", "druid"],
  "instant summons": ["wizard"],
  "irresistible dance": ["bard"],
  "magic jar": ["wizard"],
  "mass suggestion": ["bard", "sorcerer", "warlock", "wizard"],
  "move earth": ["druid", "sorcerer", "wizard"],
  "planar ally": ["cleric"],
  "primordial ward": ["druid"],
  "programmed illusion": ["bard", "wizard"],
  "sunbeam": ["druid", "sorcerer", "wizard"],
  "transport via plants": ["druid"],
  "true seeing": ["bard", "cleric", "sorcerer", "warlock", "wizard"],
  "wall of ice": ["wizard"],
  "wall of thorns": ["druid"],
  "wind walk": ["druid"],
  "word of recall": ["cleric"],

  // Level 7
  "conjure celestial": ["cleric"],
  "crown of stars": ["sorcerer", "warlock", "wizard"],
  "delayed blast fireball": ["sorcerer", "wizard"],
  "divine word": ["cleric"],
  "etherealness": ["bard", "cleric", "sorcerer", "warlock", "wizard"],
  "finger of death": ["sorcerer", "warlock", "wizard"],
  "fire storm": ["cleric", "druid", "sorcerer"],
  "forcecage": ["bard", "warlock", "wizard"],
  "mirage arcane": ["bard", "druid", "wizard"],
  "mordenkainen's magnificent mansion": ["bard", "wizard"],
  "mordenkainen's sword": ["bard", "wizard"],
  "plane shift": ["cleric", "druid", "sorcerer", "warlock", "wizard"],
  "prismatic spray": ["sorcerer", "wizard"],
  "project image": ["bard", "wizard"],
  "regenerate": ["bard", "cleric", "druid"],
  "resurrection": ["bard", "cleric"],
  "reverse gravity": ["druid", "sorcerer", "wizard"],
  "sequester": ["wizard"],
  "simulacrum": ["wizard"],
  "symbol": ["bard", "cleric", "wizard"],
  "teleport": ["bard", "sorcerer", "wizard"],
  "temple of the gods": ["cleric"],
  "whirlwind": ["druid", "sorcerer", "wizard"],

  // Level 8
  "animal shapes": ["druid"],
  "antimagic field": ["cleric", "wizard"],
  "antipathy/sympathy": ["druid", "wizard"],
  "clone": ["wizard"],
  "control weather": ["cleric", "druid", "wizard"],
  "demiplane": ["warlock", "wizard"],
  "dominate monster": ["bard", "sorcerer", "warlock", "wizard"],
  "earthquake": ["cleric", "druid", "sorcerer"],
  "feeblemind": ["bard", "druid", "warlock", "wizard"],
  "glibness": ["bard", "warlock"],
  "holy aura": ["cleric"],
  "incendiary cloud": ["sorcerer", "wizard"],
  "maddening darkness": ["warlock", "wizard"],
  "maze": ["wizard"],
  "mind blank": ["bard", "wizard"],
  "power word stun": ["bard", "sorcerer", "warlock", "wizard"],
  "sunburst": ["druid", "sorcerer", "wizard"],
  "telepathy": ["wizard"],
  "tsunami": ["druid"],

  // Level 9
  "astral projection": ["cleric", "warlock", "wizard"],
  "foresight": ["bard", "druid", "warlock", "wizard"],
  "gate": ["cleric", "sorcerer", "wizard"],
  "imprisonment": ["warlock", "wizard"],
  "invulnerability": ["wizard"],
  "mass heal": ["cleric"],
  "mass polymorph": ["bard", "sorcerer", "wizard"],
  "meteor swarm": ["sorcerer", "wizard"],
  "power word heal": ["bard", "cleric"],
  "power word kill": ["bard", "sorcerer", "warlock", "wizard"],
  "prismatic wall": ["wizard"],
  "psychic scream": ["bard", "sorcerer", "warlock", "wizard"],
  "shapechange": ["druid", "wizard"],
  "storm of vengeance": ["druid"],
  "time stop": ["sorcerer", "wizard"],
  "true polymorph": ["bard", "warlock", "wizard"],
  "true resurrection": ["cleric", "druid"],
  "weird": ["warlock", "wizard"],
  "wish": ["sorcerer", "wizard"],
};

/**
 * Get all spells for a specific class
 */
export function getSpellNamesForClass(className: string): Set<string> {
  const normalizedClass = className.toLowerCase();
  const spellNames = new Set<string>();

  for (const [spellName, classes] of Object.entries(CLASS_SPELL_LISTS)) {
    if (classes.includes(normalizedClass)) {
      spellNames.add(spellName.toLowerCase());
    }
  }

  return spellNames;
}

/**
 * Check if a spell is available to a class
 */
export function isSpellAvailableToClass(spellName: string, className: string): boolean {
  const normalizedSpell = spellName.toLowerCase();
  const normalizedClass = className.toLowerCase();
  const classes = CLASS_SPELL_LISTS[normalizedSpell];
  return classes ? classes.includes(normalizedClass) : false;
}
